dist: trusty
language: node_js

addons:
  apt:
    packages:
      - python3

node_js:
  - "4.4"

before_script:
  - npm install -g flow-bin eslint eslint-plugin-flowtype babel-eslint eslint-plugin-standard eslint-plugin-promise

env:
  - GOAL=zip
  - GOAL=flow
  - GOAL=eslint

script: make $GOAL

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
