sudo: false
language: node_js

addons:
  apt:
    packages:
      - python3

node_js:
  - "4.4"

before_script:
  - npm install -g flow-bin eslint eslint-plugin-flow-vars babel-eslint@6.0.0-beta.6 eslint-plugin-standard eslint-plugin-promise

env:
  - GOAL=zip
  - GOAL=flow
  - GOAL=eslint

script: make $GOAL 
